spring:
  application:
    name: springai

  profiles:
    active: dev

  ai:
    # Chat Models
    deepseek:
      api-key: ${modelArgs.models.deepseek.api-key}
      base-url: ${modelArgs.models.deepseek.base-url}
      chat:
        options:
          model: ${modelArgs.models.deepseek.name}
    dashscope:
      api-key: ${modelArgs.models.qwen.api-key}
      chat:
        options:
          model: ${modelArgs.models.qwen.name}
    # Embedding Model
    zhipuai:
      api-key: ${modelArgs.models.zhipuai-embed.api-key}
      embedding:
        options:
          model: ${modelArgs.models.zhipuai-embed.name}
          dimensions: ${modelArgs.models.zhipuai-embed.dimensions}
        base-url: ${modelArgs.models.zhipuai-embed.base-url}
      chat:
        options:
          model: glm-4.5

    vectorstore:
      redis:
        initialize-schema: true # 启动时自动创建Redis向量索引结构（首次部署需开启）
        index-name: xurx-index  # Redis键名前缀，用于区分不同应用的向量数据
        prefix: xurx-prefix # Redis向量索引名称

    # MCP Server 配置
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:8081

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:sql/schema-mysql.sql
    model:
      audio:
        speech: none

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}

  data:
    redis:
      host: ${data.redis.host}
      port: ${data.redis.port}
      password: ${data.redis.password}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xurx.springai.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    io.modelcontextprotocol: DEBUG
#    org.springframework.ai.mcp: DEBUG
    org.springframework.ai: DEBUG
#    org.springframework.ai.chat.client: DEBUG
#    com.xurx.springai: DEBUG

# Actuator configuration
management:
  endpoints:
    web:
      base-path: /actuator
  endpoint:
    health:
      show-details: always


server:
  port: 8080
