# Chat model
modelArgs:
  models:
    deepseek:
      name: deepseek-chat
      api-key: sk-a8ce68b04d0b48de9f9744fd75b8eb5d
      base-url: https://api.deepseek.com
    qwen:
      name: qwen-flash
      api-key: sk-2fa9861770df4d6d9b74dc3072d6f4da
      base-url: https://dashscope.aliyuncs.com

    # Embedding model
    zhipuai-embed:
        name: embedding-3
        api-key: e4ced7231ebd494fb017837f28dbb2af.BERoUfpdNHrPcq4W
        base-url: https://open.bigmodel.cn/api/paas
        dimensions: 1024

# Redis configuration
data:
    redis:
        host: 121.4.81.211
        port: 6380
        password: 123456

# MySQL configuration
datasource:
  url: jdbc:mysql://localhost:3306/springai
  username: root
  password: 1028