# Chat model
modelArgs:
  models:
    deepseek:
      name: deepseek-chat
      api-key: sk-f1166e788d72486ab7639073764c4ce2
      base-url: https://api.deepseek.com
    qwen:
      name: qwen-flash
      api-key: sk-d688c880e7824ccca2c001be7dc8ef16
      base-url: https://dashscope.aliyuncs.com/compatible-mode

    # Embedding model
    zhipuai-embed:
        name: embedding-3
        api-key: 5f0e3d6f6bb84a78b4925e1afaf8dabe.whd7LOwJ6JH6uU9V
        base-url: https://open.bigmodel.cn/api/paas
        dimensions: 1024

# Redis configuration
data:
    redis:
        host: 121.4.81.211
        port: 6380
        password: 123456